openapi: 3.0.0
info:
  title: '001'
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /Establishments:
    get:
      summary: Get
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  EstablishmentsDataTransfer:
                    type: array
                    items:
                      type: object
                      properties:
                        Id:
                          type: number
                        Description:
                          type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  ErrorList:
                    type: array
                    items:
                      type: object
                      properties:
                        Id:
                          type: number
                        Description:
                          type: string
      description: Listar Estabelecimentos
    post:
      summary: Post
      tags: []
      responses: {}
      description: Incluir Estabelecimentos
components:
  schemas: {}
