openapi: 3.0.0
info:
  title: '001'
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /Establishments:
    get:
      summary: Get
      tags: &ref_0 []
      responses: {}
      description: Listar Estabelecimentos
    post:
      summary: Post
      tags: *ref_0
      responses: {}
      description: Incluir Estabelecimentos
components:
  schemas: {}
